### ISSUE TITLE
Issue with passing list of scopes as an array item

### ISSUE THREAD

**Issue by Defrothew** [stevenmaguire/oauth2-uber#1]
Thanks for this package by the way. :)

I was having issues passing multiple scopes for the array key 'scope' supplied for getAuthorizationUrl() method. I found the issue is that when passing multiple scopes as an array item for each, it somehow implodes it and separates it in COMMA and not space as what Uber API is expecting.

So for example:
$provider->getAuthorizationUrl(array(
     'scope' => array('profile', 'request')
));
It encodes in the url as:
profile%2Crequest

Instead, it should be:
profile%20request

**Comment by Defrothew** [comment]
My temporary fix for this is:
$provider->getAuthorizationUrl(array(
'scope' => array('profile request')
));

**Comment by stevenmaguire** [comment]
Thanks for this. It's a trivial change and your workaround is effective. Can you share a link in Ubers documentation that defines this format?

**Comment by stevenmaguire** [comment]
Found it here: https://developer.uber.com/docs/ride-requests/guides/authentication/introduction#step-one-authorize

> Space delimited list of grant scopes you would like to have permission to access on behalf of the user. If none are provided the default is the set selected in your application's dashboard. It is invalid to provide no scopes and have none selected in the dashboard.

Oversight on my part. Update coming in a moment.

**Comment by stevenmaguire** [comment]
Please update your project to depend on the latest version: https://github.com/stevenmaguire/oauth2-uber/releases/tag/0.2.1
