### ISSUE TITLE
 Class 'Stevenmaguire\OAuth2\Client\Provider\Uber' not found

### ISSUE THREAD

**Issue by ivishal3258** [stevenmaguire/oauth2-uber#2]
I am using this on PHP 5.6 but i am getting the error mention in subject. Can anyone tell me the step by step integration  that  would be helpful for me .

I am using **oauth2-uber** and for this first i have installed " composer require stevenmaguire/oauth2-uber " file through composer then i have written the code as provided there for "Authorization Code Flow "and then when i trying to run this code i am getting this error.

Please help me out here.

**Comment by ivishal3258** [comment]
Hi there

      I am waiting for the response. Please help me out here asap.

Error:-
--------
**Class 'Stevenmaguire\OAuth2\Client\Provider\Uber' not found**

**Comment by stevenmaguire** [comment]
I will work with you in the other issue. Spamming these issues will not help your issue get resolved sooner.
